help([==[

Description
===========
SkyMaker is a program that simulates astronomical images. It accepts object lists in ASCII generated by the Stuff program to produce realistic astronomical fields.


More information
================
 - Homepage: https://www.astromatic.net/software/skymaker
]==])

whatis([==[Description: SkyMaker is a program that simulates astronomical images. It accepts object lists in ASCII generated by the Stuff program to produce realistic astronomical fields.]==])
whatis([==[Homepage: https://www.astromatic.net/software/skymaker]==])

local root = "/apps/knl/software/mpi/gcc/6.4.0/openmpi/3.0.0/skymaker/3.3.3"

conflict("skymaker")

if not isloaded("openblas/0.2.20") then
    load("openblas/0.2.20")
end

if not isloaded("fftw/3.3.7") then
    load("fftw/3.3.7")
end

if not isloaded("scalapack/2.0.2-openblas-0.2.20") then
    load("scalapack/2.0.2-openblas-0.2.20")
end

prepend_path("MANPATH", pathJoin(root, "share/man"))
prepend_path("PATH", pathJoin(root, "bin"))
setenv("EBROOTSKYMAKER", root)
setenv("EBVERSIONSKYMAKER", "3.3.3")
setenv("EBDEVELSKYMAKER", pathJoin(root, "easybuild/mpi-gcc-6.4.0-openmpi-3.0.0-skymaker-3.3.3-easybuild-devel"))

-- Built with EasyBuild version 3.6.1.dev0
